In [5]:
import pandas as pd

url = "https://raw.githubusercontent.com/plotly/datasets/master/fips-unemp-16.csv"
df_real = pd.read_csv(url, dtype={"fips": str})

df_real.head()

    fips  unemp
0  01001    5.3
1  01003    5.4
2  01005    8.6
3  01007    6.6
4  01009    5.5

# Assistant
The error is a syntax error on line 1 of your code. The issue is that you've misspelled the import statement as "iimport" instead of "import".

Would you like me to provide the corrected code?

In [6]:
df_real["fips"] = df_real["fips"].astype(str).str.zfill(5)
df_real.head()

    fips  unemp
0  01001    5.3
1  01003    5.4
2  01005    8.6
3  01007    6.6
4  01009    5.5

In [7]:
df_real.columns

Index(['fips', 'unemp'], dtype='object')

In [8]:
import plotly.express as px

fig = px.choropleth(
    df_real,
    geojson=counties,
    locations="fips",
    color="unemp",             # if your columns show a different name, tell me and we’ll swap it
    scope="usa",
    color_continuous_scale="Viridis",
    labels={"unemp": "Rate"},
)

fig.update_layout(
    title="County map (real dataset)",
    margin={"r":0,"t":50,"l":0,"b":0},
)

fig.show()

NameError: name 'counties' is not defined

In [9]:
import json

with open("../data/raw/geo/geojson-counties-fips.json", "r") as f:
    counties = json.load(f)

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/geo/geojson-counties-fips.json'

In [10]:
import json

    with open("../data/raw/geo/geojson-counties-fips.json", "r") as f:
    counties = json.load(f)

IndentationError: unexpected indent (3146567010.py, line 3)

In [11]:
import json

with open("../data/raw/geo/geojson-counties-fips.json", "r") as f:
    counties = json.load(f)

FileNotFoundError: [Errno 2] No such file or directory: '../data/raw/geo/geojson-counties-fips.json'

In [12]:
import os
os.getcwd()

'/Users/zoomuser1/Desktop/hiv-need-access-eda/notebooks/notebooks'

In [13]:
import os

In [14]:
import os
os.listdir(".")

['02_county_map.ipynb',
 '.ipynb_checkpoints',
 '01_smoke_test.ipynb',
 '02_county_map_smoke_test.ipynb']